env:
  - TEST_DATABASE_URL='postgresql:///stoic_test'
services:
  - postgresql
before_script:
  - psql -c 'create database stoic_test;' -U postgres
  - psql -d stoic_test -c "CREATE EXTENSION postgis;"
  - psql -d stoic_test -c "CREATE EXTENSION postgis_topology;"
language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: 
  - coverage run --source app/ ./manage.py test
after_success:
  coveralls
