services:
  - cassandra
language: python
python:
  - "3.5"
cache: pip
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install pytest"
  - "python setup.py develop"
script: 
  - py.test test/ -v
  - coverage run --source app/ ./manage.py test
after_success:
  coveralls
