services:
  - redis-server
  - docker
language: python
python:
  - "3.5"
cache: pip
addons:  
  apt:
   packages:
    - oracle-java8-installer
before_install:    
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.10/apache-cassandra-3.10-bin.tar.gz && tar -xvzf apache-cassandra-3.10-bin.tar.gz
  - sudo sh ./apache-cassandra-3.10/bin/cassandra -R
  - sleep 20
install:
  - "pip install -r dev-requirements.txt"
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script: 
  - mkdir csv_files
  - py.test --pep8 geo
  - py.test -v --cov=geo --cov-report term-missing --pep8 test
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t kolbman.xyz:3333/geo .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
    docker push kolbman.xyz:3333/geo;
    fi
