services:
  - cassandra
language: python
python:
  - "3.5"
cache: pip
install:
  - "pip install -r dev-requirements.txt"
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script: 
  - py.test -v --cov=app --cov-report term-missing test
after_success:
  coveralls
